name = "edgetunnel-nat64-do"
main = "src/worker.js"
compatibility_date = "2026-01-20"

[vars]
UUID = "d87484d1-77a6-40bb-bac6-5b574bd7f61c"
NAT64_PREFIX = "2602:fc59:b0:64::"
REGION = "wnam"
BESTIP = "saas.sin.fan"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["WsDo"]

[durable_objects]
	bindings = [
		{ class_name = "WsDo", name = "WS_DO" }
	]
