name = "test"
main = "src/worker.js"
compatibility_date = "2026-01-20"
preview_urls = false

[vars]
UUID = "d87484d1-77a6-40bb-bac6-5b574bd7f61c"
PROXYIP = "[2602:fc59:11:64::6810:0]"
REGION = "wnam"
BESTIP = "cf.877774.xyz"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["WsDo"]

[durable_objects]
	bindings = [
		{ class_name = "WsDo", name = "WS_DO" }
	]
